# Generated by Django 6.0.1 on 2026-02-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_company', '0001_initial'),
        ('technic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTechnicalMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип технического обслуживания',
                'verbose_name_plural': 'Типы технического обслуживания',
            },
        ),
        migrations.CreateModel(
            name='TechnicalMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_maintenance', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.PositiveIntegerField(default=0, verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=200, unique=True, verbose_name='№ заказ-наряда')),
                ('date_order_number', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.machine', verbose_name='Машина')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_company.servicecompany', verbose_name='Техническое обслуживание')),
                ('type_technical_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_maintenance.typetechnicalmaintenance', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Техническое обслуживание',
            },
        ),
    ]
