# Generated by Django 6.0.1 on 2026-02-24 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_company', '0002_alter_servicecompany_options'),
        ('technical_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_company.servicecompany', verbose_name='Сервисная компания'),
        ),
    ]
