# Generated by Django 6.0.1 on 2026-03-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='date_order_number',
            field=models.DateTimeField(verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='order_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='№ заказ-наряда'),
        ),
    ]
