# Generated by Django 6.0.1 on 2026-03-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_maintenance', '0002_alter_technicalmaintenance_service_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='date_maintenance',
            field=models.DateTimeField(verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='date_order_number',
            field=models.DateTimeField(verbose_name='Дата заказ-наряда'),
        ),
    ]
