# Generated by Django 6.0.1 on 2026-02-04 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('number_machine', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('number_engine', models.CharField(max_length=200, unique=True)),
                ('number_transmission', models.CharField(max_length=200, unique=True)),
                ('number_driving_bridge', models.CharField(max_length=200, unique=True)),
                ('number_controlled_bridge', models.CharField(max_length=200, unique=True)),
                ('delivery_agreement', models.CharField(max_length=300)),
                ('date_shipment', models.DateField()),
                ('end_user', models.CharField(max_length=500)),
                ('delivery_address', models.CharField(max_length=500)),
                ('Equipment', models.CharField(max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model_controlled_bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.controlledbridge')),
                ('model_driving_bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.drivingbridge')),
                ('model_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.engine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_company.servicecompany')),
                ('model_technic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.technic')),
                ('model_transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.transmission')),
            ],
        ),
    ]
