# Generated by Django 6.0.1 on 2026-02-05 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, unique=True, verbose_name='Модель')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Управляемый мост',
                'verbose_name_plural': 'Управляемые мосты',
            },
        ),
        migrations.CreateModel(
            name='DrivingBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, unique=True, verbose_name='Модель')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ведущий мост',
                'verbose_name_plural': 'Ведущие мосты',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, unique=True, verbose_name='Модель')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Двигатель',
                'verbose_name_plural': 'Двигатели',
            },
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, unique=True, verbose_name='Модель')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Технику',
                'verbose_name_plural': 'Техника',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, unique=True, verbose_name='Модель')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Трансмиссию',
                'verbose_name_plural': 'Трансмиссии',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('number_machine', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='Зав. № машины')),
                ('number_engine', models.CharField(max_length=200, unique=True, verbose_name='Зав. № двигателя')),
                ('number_transmission', models.CharField(max_length=200, unique=True, verbose_name='Зав. № трансмиссии')),
                ('number_driving_bridge', models.CharField(max_length=200, unique=True, verbose_name='Зав. № ведущего моста')),
                ('number_controlled_bridge', models.CharField(max_length=200, unique=True, verbose_name='Зав. № управляемого моста')),
                ('delivery_agreement', models.CharField(max_length=300, verbose_name='Договор поставки №, дата')),
                ('date_shipment', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('end_user', models.CharField(max_length=500, verbose_name='Конечный потребитель')),
                ('delivery_address', models.CharField(max_length=500, verbose_name='Адрес поставки')),
                ('Equipment', models.CharField(max_length=500, verbose_name='Комплектация')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('model_controlled_bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.controlledbridge', verbose_name='Модель управляемого моста')),
                ('model_driving_bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.drivingbridge', verbose_name='Модель ведущего моста')),
                ('model_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.engine', verbose_name='Модель двигателя')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_company.servicecompany', verbose_name='Сервисная компания')),
                ('model_technic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.technic', verbose_name='Модель техники')),
                ('model_transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.transmission', verbose_name='Модель трансмиссии')),
            ],
            options={
                'verbose_name': 'Машину',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
