# Generated by Django 6.0.1 on 2026-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='delivery_agreement',
            field=models.CharField(max_length=300, unique=True, verbose_name='Договор поставки №, дата'),
        ),
    ]
