# Generated by Django 6.0.1 on 2026-03-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technic', '0002_alter_machine_delivery_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlledbridge',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='drivingbridge',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
