# Generated by Django 6.0.1 on 2026-03-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technic', '0003_alter_controlledbridge_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='Equipment',
            field=models.TextField(max_length=500, verbose_name='Комплектация'),
        ),
    ]
