# Generated by Django 6.0.1 on 2026-03-16 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_company', '0005_alter_servicecompanyprofile_options'),
        ('technic', '0004_alter_machine_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('number_engine',), name='unique_number_engine', violation_error_message='Двигатель с таким номером уже есть'),
        ),
    ]
