# Generated by Django 6.0.1 on 2026-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technic', '0006_alter_machine_number_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='number_engine',
            field=models.CharField(max_length=200, unique=True, verbose_name='Зав. № двигателя'),
        ),
    ]
