# Generated by Django 6.0.1 on 2026-03-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technic', '0008_alter_machine_unique_number_engine'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='machine',
            name='unique_number_engine',
        ),
    ]
