# Generated by Django 6.0.1 on 2026-03-16 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_company', '0005_alter_servicecompanyprofile_options'),
        ('technic', '0009_remove_machine_unique_number_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('number_engine',), name='unique_number_engine', violation_error_message='Ошибка!!!'),
        ),
    ]
