# Generated by Django 6.0.1 on 2026-03-16 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_company', '0005_alter_servicecompanyprofile_options'),
        ('technic', '0010_machine_unique_number_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('number_transmission',), name='unique_number_transmission', violation_error_message='Ошибка!!! number_transmission'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('number_driving_bridge',), name='number_driving_bridge', violation_error_message='Ошибка!!! number_driving_bridge'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('number_controlled_bridge',), name='number_controlled_bridge', violation_error_message='Ошибка!!! number_controlled_bridge'),
        ),
    ]
