# Generated by Django 6.0.1 on 2026-03-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technic', '0011_machine_unique_number_transmission_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='machine',
            name='unique_number_engine',
        ),
        migrations.RemoveConstraint(
            model_name='machine',
            name='unique_number_transmission',
        ),
        migrations.RemoveConstraint(
            model_name='machine',
            name='number_driving_bridge',
        ),
        migrations.RemoveConstraint(
            model_name='machine',
            name='number_controlled_bridge',
        ),
    ]
