# Generated by Django 6.0.1 on 2026-03-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technic', '0012_remove_machine_unique_number_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='delivery_agreement',
            field=models.CharField(max_length=300, verbose_name='Договор поставки №, дата'),
        ),
    ]
