# Generated by Django 6.0.1 on 2026-02-04 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_company', '0001_initial'),
        ('technic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='technic.machine')),
                ('date_failure', models.DateField()),
                ('operating_time', models.PositiveIntegerField(default=0)),
                ('description_failure', models.TextField()),
                ('used_parts', models.TextField()),
                ('date_restoration', models.DateField()),
                ('downtime', models.PositiveIntegerField(default=0)),
                ('machine', models.CharField(max_length=200)),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_company.servicecompany')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.failurenode')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.recoverymethod')),
            ],
        ),
    ]
