# Generated by Django 6.0.1 on 2026-02-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_company', '0001_initial'),
        ('technic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
                'verbose_name_plural': 'Узлы отказа',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Метод восстановления',
                'verbose_name_plural': 'Методы восстановления',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_failure', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('description_failure', models.TextField(verbose_name='Описание отказа')),
                ('used_parts', models.TextField(verbose_name='Используемые запчасти')),
                ('date_restoration', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.PositiveIntegerField(default=0, verbose_name='Время простоя техники')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.machine', verbose_name='Машина')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_company.servicecompany', verbose_name='Сервисная компания')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.failurenode', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.recoverymethod', verbose_name='Способ восстановления')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
    ]
