# Generated by Django 6.0.1 on 2026-03-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_failure',
            field=models.DateTimeField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_restoration',
            field=models.DateTimeField(verbose_name='Дата восстановления'),
        ),
    ]
