# Generated by Django 6.0.1 on 2026-03-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_alter_complaint_date_failure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_restoration',
            field=models.DateTimeField(null=True, verbose_name='Дата восстановления'),
        ),
    ]
