# Generated by Django 6.0.1 on 2026-03-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_alter_complaint_date_restoration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='used_parts',
            field=models.TextField(null=True, verbose_name='Используемые запчасти'),
        ),
    ]
