# Generated by Django 6.0.1 on 2026-03-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_alter_complaint_used_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_restoration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата восстановления'),
        ),
    ]
