# Generated by Django 6.0.1 on 2026-02-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecompany',
            options={'verbose_name': 'Сервисную компанию', 'verbose_name_plural': 'Сервисные компании'},
        ),
    ]
