# Generated by Django 6.0.1 on 2026-03-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_company', '0004_remove_servicecompany_user_servicecompanyprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecompanyprofile',
            options={'verbose_name': 'Профиль СК', 'verbose_name_plural': 'Профили СК'},
        ),
    ]
